comment: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "src/cpyrt/PyObjectDir27.inc"   # vendored PSF code

component_management:
  individual_components:
    - component_id: cpyrt
      name: cpyrt
      paths: ["src/cpyrt/**"]
    - component_id: interop
      name: interop
      paths: ["src/interop/**"]
    - component_id: python
      name: python
      paths: ["python/cppjit/**"]
